# Stratified Sampling

Stratified Sampling is a sampling technique used to obtain samples that best represent the population. It reduces bias in selecting samples by dividing the population into homogeneous subgroups called strata, and randomly sampling data from each stratum(singular form of strata). In statistics, stratified sampling is used when the mean values of each stratum will differ.

For example, the VOTO dataset contains answers from people who were asked questions after voting. We can use strafification to create a subsample were, for example, the age groups are representative for the age distribution across the whole dataset. 

- **Goal:** We need to get a representative sample with a size of 1500 data points of the data distribution for the properties `age_category`, `part` and `educ`.

For more infos see [here](https://codepointtech.com/mastering-stratified-sampling-in-pandas-for-representative-data/) and [here](https://www.geeksforgeeks.org/python/stratified-sampling-in-pandas/)

In [1]:
import pandas as pd
# avoid scientific notation number format
pd.set_option("display.float_format", lambda x: f"{x:.6f}")

In [4]:
#loading data
voto_project = "./data/data_reduced_coding1.csv"
df = pd.read_csv(voto_project)

print("data set length:", (len(df)))
df.head()

data set length: 47147

,id,date,proposalx,d1e1,d2e1,d3e1,turnoutx,titel_kurz_d,age,age_category,part,vote_x,educ
0,1220001.000000,2016-09-25,605,9,7.000000,NaN,42.998523,Initiative «Grüne Wirtschaft»,46.000000,class45,did not,NaN,5
1,1220002.000000,2016-09-25,605,9,7.000000,NaN,42.998523,Initiative «Grüne Wirtschaft»,23.000000,class18,did not,NaN,6
2,1220003.000000,2016-09-25,605,9,7.000000,NaN,42.998523,Initiative «Grüne Wirtschaft»,70.000000,class65,did,no (rejected),7
3,1220004.000000,2016-09-25,605,9,7.000000,NaN,42.998523,Initiative «Grüne Wirtschaft»,58.000000,class55,did not,NaN,5
4,1220005.000000,2016-09-25,605,9,7.000000,NaN,42.998523,Initiative «Grüne Wirtschaft»,57.000000,class55,did,don’t know,5

## Understanding data distribution

We can use the `value_counts` function to understand the distribution of each category in our dataset. This will help us validate the subsample we created afterwards.

In [3]:
print("\nOriginal age_category Distribution:")
print(df["age_category"].value_counts(normalize=True))
print("\nOriginal part Distribution:")
print(df["part"].value_counts(normalize=True))
print("\nOriginal educ Distribution:")
print(df["educ"].value_counts(normalize=True))

Original age_category Distribution:
age_category
class55   0.196598
class65   0.196046
class45   0.186078
class75   0.144442
class35   0.118056
class18   0.087598
class25   0.071182
Name: proportion, dtype: float64

Original part Distribution:
part
did       0.705241
did not   0.294759
Name: proportion, dtype: float64

Original educ Distribution:
educ
5    0.407831
9    0.239867
8    0.108024
6    0.093028
2    0.086898
10   0.021041
4    0.015335
7    0.010690
3    0.007614
1    0.005175
0    0.002439
99   0.002057
Name: proportion, dtype: float64

## Proportionate sampling

Using pandas groupby, separate the participants into groups based on their age_category and random sample from each group based on population proportion. The total sample size is 60%(0.6) of the data set size

In [ ]:
prop_sample = df.groupby("age_category").apply(lambda x: x.sample(frac=0.6, replace=False))
prop_sample.head()

/var/folders/_r/k49wtlq94ydc3vksghsj67ym0000gn/T/ipykernel_58422/2421866700.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  prop_sample = df.groupby("age_category").apply(lambda x: x.sample(frac=0.6, replace=False))

                               id        date  proposalx  d1e1      d2e1  \
age_category
class18      41472 1340378.000000  2020-09-27        632     5  9.000000
             39172 1331097.000000  2020-02-09        630    10  1.000000
             20694 1280743.000000  2018-06-10        618     1  4.000000
             39930 1340349.000000  2020-09-27        631     2 10.000000
             34898 1321367.000000  2019-05-19        627     6 10.000000

                       d3e1  turnoutx  \
age_category
class18      41472      NaN 59.324371
             39172      NaN 41.679213
             20694      NaN 34.553721
             39930      NaN 59.471181
             34898 4.000000 43.737242

                                                         titel_kurz_d  \
age_category
class18      41472                                         Jagdgesetz
             39172  Verbot der Diskriminierung aufgrund der sexuel...
             20694                                Vollgeld-Initiative
             39930                              Begrenzungsinitiative
             34898           Steuerreform und AHV-Finanzierung (STAF)

                         age age_category     part         vote_x  educ
age_category
class18      41472 20.000000      class18  did not            NaN     5
             39172 24.000000      class18  did not            NaN     9
             20694 22.000000      class18  did not            NaN     5
             39930 20.000000      class18      did  no (rejected)     6
             34898 20.000000      class18  did not            NaN     6

Now compare the samples data distribution with the above distribution to validate our sampling process. It is surprisingly accurate! 🤗

In [ ]:
print("sample data length", len(prop_sample))
print("\nSample age category Distribution:")
print(prop_sample["age_category"].value_counts(normalize=True))

sample data length 28289

Sample age category Distribution:
age_category
class55   0.196578
class65   0.196048
class45   0.186079
class75   0.144438
class35   0.118067
class18   0.087596
class25   0.071194
Name: proportion, dtype: float64

## Proportionate sampling for multiple values

What if you need to stratify by more than one characteristic? For example, you might want to ensure representation by "educ" AND "age_category" simultaneously. Pandas handles this elegantly by passing a list of column names to groupby().

In [15]:
prop_sample_2 = df.groupby(["age_category", "part", "educ"]).apply(lambda x: x.sample(frac=0.6, replace=False))
prop_sample_2.head()

/var/folders/_r/k49wtlq94ydc3vksghsj67ym0000gn/T/ipykernel_58422/1854298778.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  prop_sample_2 = df.groupby(["age_category", "part", "educ"]).apply(lambda x: x.sample(frac=0.6, replace=False))

                                         id        date  proposalx  d1e1  \
age_category part educ
class18      did  1    23810 1290841.000000  2018-09-23        620     8
                       25312 1290841.000000  2018-09-23        621     5
                  2    14392 1260525.000000  2017-09-24        614    10
                       32026 1310012.000000  2019-02-10        626     9
                       30374 1301386.000000  2018-11-25        624     1

                                 d2e1     d3e1  turnoutx  \
age_category part educ
class18      did  1    23810      NaN      NaN 37.447463
                       25312      NaN      NaN 37.473439
                  2    14392 6.000000      NaN 47.394480
                       32026      NaN      NaN 37.927738
                       30374 2.000000 1.000000 48.408746

                                                                   titel_kurz_d  \
age_category part educ
class18      did  1    23810  Bundesbeschluss über die Velowege sowie die Fu...
                       25312                               Fair-Food-Initiative
                  2    14392  Zusatzfinanzierung der AHV durch eine Erhöhung...
                       32026                            Zersiedelungsinitiative
                       30374                        Selbstbestimmungsinitiative

                                   age age_category part  \
age_category part educ
class18      did  1    23810 18.000000      class18  did
                       25312 18.000000      class18  did
                  2    14392 18.000000      class18  did
                       32026 19.000000      class18  did
                       30374 19.000000      class18  did

                                                                         vote_x  \
age_category part educ
class18      did  1    23810                                     yes (accepted)
                       25312                                     yes (accepted)
                  2    14392                                     yes (accepted)
                       32026  voted blank / did not vote for this voting pro...
                       30374                                      no (rejected)

                              educ
age_category part educ
class18      did  1    23810     1
                       25312     1
                  2    14392     2
                       32026     2
                       30374     2

again we can verify the distributions of our samples data with the complete data distribution. Yaay! 🎈

In [16]:
print("\n Sample age_category Distribution:")
print(prop_sample_2["age_category"].value_counts(normalize=True))
print("\nSample part Distribution:")
print(prop_sample_2["part"].value_counts(normalize=True))
print("\n Sample educ Distribution:")
print(prop_sample_2["educ"].value_counts(normalize=True))

 Sample age_category Distribution:
age_category
class55   0.196613
class65   0.196047
class45   0.186077
class75   0.144428
class35   0.118053
class18   0.087576
class25   0.071206
Name: proportion, dtype: float64

Sample part Distribution:
part
did       0.705346
did not   0.294654
Name: proportion, dtype: float64

 Sample educ Distribution:
educ
5    0.407828
9    0.239924
8    0.108012
6    0.093056
2    0.086834
10   0.021001
4    0.015309
7    0.010677
3    0.007601
1    0.005197
0    0.002475
99   0.002086
Name: proportion, dtype: float64

## Set sample size & export

We use the `frac` value to approach a specific sample size, e.g. 1500

In [ ]:
final_sample = df.groupby(["age_category", "part", "educ"], group_keys=False).apply(lambda x: x.sample(frac=0.03194, replace=False))
print(len(final_sample))

final_sample

1500

/var/folders/_r/k49wtlq94ydc3vksghsj67ym0000gn/T/ipykernel_58422/3435603030.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  final_sample = df.groupby(["age_category", "part", "educ"], group_keys=False).apply(lambda x: x.sample(frac=0.03194, replace=False))

,id,date,proposalx,d1e1,d2e1,d3e1,turnoutx,titel_kurz_d,age,age_category,part,vote_x,educ
4506,1221357.000000,2016-09-25,607,3,1.000000,NaN,42.943712,Nachrichtendienstgesetz,18.000000,class18,did,don’t know,2
45722,1340089.000000,2020-09-27,635,3,6.000000,NaN,59.405366,Beschaffung neuer Kampfflugzeuge,18.000000,class18,did,no (rejected),2
27805,1300330.000000,2018-11-25,623,5,9.000000,NaN,48.300109,Hornkuh-Initiative,18.000000,class18,did,no (rejected),2
6440,1240138.000000,2017-02-12,609,1,10.000000,NaN,46.844365,Erleichterte Einbürgerung der dritten Auslände...,18.000000,class18,did,yes (accepted),2
7628,1241326.000000,2017-02-12,609,1,10.000000,NaN,46.844365,Erleichterte Einbürgerung der dritten Auslände...,20.000000,class18,did,yes (accepted),2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32533,1310519.000000,2019-02-10,626,9,NaN,NaN,37.927738,Zersiedelungsinitiative,79.000000,class75,did not,NaN,8
5918,1231194.000000,2016-11-27,608,7,NaN,NaN,45.383720,Atomausstiegsinitiative,77.000000,class75,did not,NaN,9
42893,1340286.000000,2020-09-27,633,6,10.000000,NaN,59.189482,Erhöhung der steuerlichen Kinderabzüge,83.000000,class75,did not,NaN,9
24455,1291486.000000,2018-09-23,620,8,NaN,NaN,37.447463,Bundesbeschluss über die Velowege sowie die Fu...,76.000000,class75,did not,NaN,9
34329,1320798.000000,2019-05-19,627,6,10.000000,4.000000,43.737242,Steuerreform und AHV-Finanzierung (STAF),89.000000,class75,did not,NaN,10

In [38]:
final_sample.to_csv("./export/proportional-sample.csv", index=False)