# Wetterdaten-Downlaod

Wir arbeiten mit Wetterdaten der Stadt Zürich. 

Quelle: https://data.stadt-zuerich.ch/dataset/ugz_meteodaten_tagesmittelwerte/resource/0c200920-8500-4049-8230-cf8b53a61791 <br>
Metadaten: https://data.stadt-zuerich.ch/dataset/ugz_meteodaten_tagesmittelwerte/download/uzg_ogd_metadaten.json

Was hier passiert
1. Jahr 2024 Download
2. Mehrere Jahre Download
3. Abspeichern

In [5]:
import pandas as pd
import requests

## Ein Jahr herunterladen

In [6]:
# Wir schauen uns die Daten von 2024 an.

# url definieren
url = 'https://data.stadt-zuerich.ch/api/3/action/datastore_search?resource_id=6e1405b8-5fa1-4e2f-b9fa-52f0796a35b0&limit=100000'

# mit requests Daten abrufen
response = requests.get(url)
# json-objekt aus der Antwort
data = response.json()

# Dataframe aus dem Json-Objekt
df = pd.DataFrame(data["result"]["records"])

In [7]:
# tada:
df.head(10)

,_id,Datum,Standort,Parameter,Intervall,Einheit,Wert,Status
0,1,2024-01-01T00:00+0100,Zch_Stampfenbachstrasse,T,d1,°C,6.27,bereinigt
1,2,2024-01-01T00:00+0100,Zch_Stampfenbachstrasse,RainDur,d1,min,64.68,bereinigt
2,3,2024-01-01T00:00+0100,Zch_Stampfenbachstrasse,p,d1,hPa,963.33,bereinigt
3,4,2024-01-01T00:00+0100,Zch_Stampfenbachstrasse,StrGlo,d1,W/m2,43.79,bereinigt
4,5,2024-01-01T00:00+0100,Zch_Stampfenbachstrasse,T_max_h1,d1,°C,8.31,bereinigt
5,6,2024-01-01T00:00+0100,Zch_Schimmelstrasse,T,d1,°C,6.27,bereinigt
6,7,2024-01-01T00:00+0100,Zch_Schimmelstrasse,RainDur,d1,min,61.52,bereinigt
7,8,2024-01-01T00:00+0100,Zch_Schimmelstrasse,p,d1,hPa,965.88,bereinigt
8,9,2024-01-01T00:00+0100,Zch_Schimmelstrasse,T_max_h1,d1,°C,8.34,bereinigt
9,10,2024-01-01T00:00+0100,Zch_Rosengartenstrasse,T,d1,°C,5.94,bereinigt

### Alle Jahre herunterladen

In [8]:
# Die Links der einzelnen Datensätze unterscheiden sich nur in ihrer ID. Deshalb listen wir diese hier auf, so dass wir sie nachher abrufen können.

# Das hier ist Handarbeit, die 35 verschiedenen IDs der einzelnen Jahre auflisten

resource_list = ['141e649c-27de-412d-ba57-7491bc162dd2',
                 '429049f8-8a54-4662-858e-5a4820af12e6',
                 '6e1405b8-5fa1-4e2f-b9fa-52f0796a35b0',
                 '4f4aec31-77af-49e2-822e-920f3e515dcb',
                 'df75d0a5-53dd-42cb-9701-46ee8706746f',
                 'bd79748f-c2df-4a0d-8d4c-2786afd5d4c3',
                 'f1cbd8d9-e3ea-44a9-bb53-ba3ef9dd9215',
                 'acb0be29-3249-4f4e-b348-b8718dda20b1',
                 '5b2c8d7e-ce3d-4d0a-ac02-630d455099ee',
                 '8e66bca3-7479-48e4-afdc-bfa536f7b9b1',
                 'e5683220-e460-4dc1-a23e-e90e6cb8de53',
                 'a5fb55fa-2363-4553-9534-9fd11d5f5805',
                 'd70fca54-fd41-4a1f-a5c9-5154bcefafd7',
                 '7a9e2f3c-b900-49cc-8539-d467c4a72c4c',
                 '7e119ab4-45e7-4327-87b4-59d1d8fb7af9',
                 '46511df7-7c52-48c1-b3d1-fdf169d9d8bb',
                 '4c71ebc9-5c2b-4eb5-9e09-67a778d260bb',
                 'a2cb7967-0a67-44b2-90e7-8dc4819b58fe',
                 '53d1bd81-61f7-4d4f-be96-da55ab4aa6a3',
                 'd8d9addc-5252-4910-ba95-a5b6317034ec',
                 'e0a1de2b-cf34-494a-baf8-d7c12446a412',
                 '106504d5-54d7-4036-84b3-57c21480323b',
                 'c9b4f0ed-e437-4b72-b02d-ca517fe688e0',
                 'a2aa21a2-45dd-4a9f-8d95-7f8bb5d652cd',
                 '4cf262b8-86c6-42f4-88fd-b4e648b19ffd',
                 '10af3de1-8613-4f8b-beae-4e3ec707f036',
                 '8f3c41e5-d0e2-41bc-b0e4-f83871f0b377',
                 'b0a252a4-96e3-4b16-b71d-6807891e8908',
                 'e1cc911b-9e34-40de-86f9-4d0d21334f90',
                 'a54ee67d-a0f3-4782-87fa-948607a98b54',
                 'f03b4943-9fb8-45d5-bad8-f3aefd0b7199',
                 '31f80392-187d-4568-a171-1f4d75d722a6',
                 'c09e8531-ce17-4ca9-9ece-49eb72962ffb',
                 '131b73e5-d2d6-40b8-9fec-44f47abd2a84',
                 '83751fa7-f5fe-4dfb-8fa2-1091366f73a5',
]

In [9]:


# leere Liste
df_ls = [] 

# Für jedes Element in der ID-Liste die Daten herunterladen und in einer DF-Liste speichern
for e,id in enumerate(resource_list): # enumerate() erlaubt, den index in der Liste jeweils anzuzeigen - hilft beim debuggen
    print(e,id) # ausprinten wo in der Liste sind
    url = 'https://data.stadt-zuerich.ch/api/3/action/datastore_search?resource_id='+ id +'&limit=100000' # <- id ist was sich jeweils in der URL ändert

    response = requests.get(url)
    data = response.json()
    this_df = pd.DataFrame(data["result"]["records"])
    df_ls.append(this_df) # <- den DF zur vormals leeren Liste hinzufügen

0 141e649c-27de-412d-ba57-7491bc162dd2
1 429049f8-8a54-4662-858e-5a4820af12e6
2 6e1405b8-5fa1-4e2f-b9fa-52f0796a35b0
3 4f4aec31-77af-49e2-822e-920f3e515dcb
4 df75d0a5-53dd-42cb-9701-46ee8706746f
5 bd79748f-c2df-4a0d-8d4c-2786afd5d4c3
6 f1cbd8d9-e3ea-44a9-bb53-ba3ef9dd9215
7 acb0be29-3249-4f4e-b348-b8718dda20b1
8 5b2c8d7e-ce3d-4d0a-ac02-630d455099ee
9 8e66bca3-7479-48e4-afdc-bfa536f7b9b1
10 e5683220-e460-4dc1-a23e-e90e6cb8de53
11 a5fb55fa-2363-4553-9534-9fd11d5f5805
12 d70fca54-fd41-4a1f-a5c9-5154bcefafd7
13 7a9e2f3c-b900-49cc-8539-d467c4a72c4c
14 7e119ab4-45e7-4327-87b4-59d1d8fb7af9
15 46511df7-7c52-48c1-b3d1-fdf169d9d8bb
16 4c71ebc9-5c2b-4eb5-9e09-67a778d260bb
17 a2cb7967-0a67-44b2-90e7-8dc4819b58fe
18 53d1bd81-61f7-4d4f-be96-da55ab4aa6a3
19 d8d9addc-5252-4910-ba95-a5b6317034ec
20 e0a1de2b-cf34-494a-baf8-d7c12446a412
21 106504d5-54d7-4036-84b3-57c21480323b
22 c9b4f0ed-e437-4b72-b02d-ca517fe688e0
23 a2aa21a2-45dd-4a9f-8d95-7f8bb5d652cd
24 4cf262b8-86c6-42f4-88fd-b4e648b19ffd
25 10af3de1-8613-4f8b-beae-4e3ec707f036
26 8f3c41e5-d0e2-41bc-b0e4-f83871f0b377
27 b0a252a4-96e3-4b16-b71d-6807891e8908
28 e1cc911b-9e34-40de-86f9-4d0d21334f90
29 a54ee67d-a0f3-4782-87fa-948607a98b54
30 f03b4943-9fb8-45d5-bad8-f3aefd0b7199
31 31f80392-187d-4568-a171-1f4d75d722a6
32 c09e8531-ce17-4ca9-9ece-49eb72962ffb
33 131b73e5-d2d6-40b8-9fec-44f47abd2a84
34 83751fa7-f5fe-4dfb-8fa2-1091366f73a5

In [11]:
# Dfs aneinanderkleben
df = pd.concat(df_ls)
# Indexe der einzelnen dfs zusammenfügen
df.reset_index(drop=True)

,_id,Datum,Standort,Parameter,Intervall,Einheit,Wert,Status
0,1,2026-01-01T00:00+0100,Zch_Heubeeribüel,T,d1,°C,-2.57,provisorisch
1,2,2026-01-01T00:00+0100,Zch_Heubeeribüel,T_max_h1,d1,°C,1.3,provisorisch
2,3,2026-01-01T00:00+0100,Zch_Heubeeribüel,p,d1,hPa,941.89,provisorisch
3,4,2026-01-01T00:00+0100,Zch_Rosengartenstrasse,RainDur,d1,min,0.0,provisorisch
4,5,2026-01-01T00:00+0100,Zch_Rosengartenstrasse,T,d1,°C,-1.97,provisorisch
...,...,...,...,...,...,...,...,...
110416,732,1992-12-30T00:00+0100,Zch_Stampfenbachstrasse,T_max_h1,d1,°C,-2.55,bereinigt
110417,733,1992-12-31T00:00+0100,Zch_Stampfenbachstrasse,StrGlo,d1,W/m2,17.25,bereinigt
110418,734,1992-12-31T00:00+0100,Zch_Stampfenbachstrasse,T,d1,°C,-3.39,bereinigt
110419,735,1992-12-31T00:00+0100,Zch_Stampfenbachstrasse,p,d1,hPa,970.69,bereinigt
110420,736,1992-12-31T00:00+0100,Zch_Stampfenbachstrasse,T_max_h1,d1,°C,-2.74,bereinigt

In [12]:
df.to_csv('data/weather/zurich_weather_1992-2026_all_values.csv', index=False)

Und wir haben unsere Daten! Weiter in 03.2_heatmap.ipynb