# Cities Exploration

In [3]:
import pandas as pd
import altair as alt

In [4]:
df_full =pd.read_csv('data/cities/merged_wide_complete.csv')

In [5]:
df_full.head()

,cities,cenv_Total number of hours of sunshine per day,cenv_Average temperature of warmest month - degrees,cenv_Average temperature of coldest month - degrees,cenv_Rainfall - litre/m²,cenv_Number of days ozone O3 concentrations exceed 120 µg/m³,cenv_Number of hours nitrogen dioxide NO2 concentrations exceed 200 µg/m³,cenv_Number of days particulate matter PM10 concentrations exceed 50 µg/m³,cenv_Accumulated ozone concentration in excess 70 µg/m³,cenv_Annual average concentration of NO2 (µg/m³),...,ctran_Average length of journey to work by private car - km,ctran_Number of registered cars per 1000 population,ctran_Number of private cars registered,ctran_People killed in road accidents per 10000 pop.,ctran_Number of deaths in road accidents,ctran_People commuting into the city,ctran_People commuting out of the city,ctran_Length of bicycle network (dedicated cycle paths and lanes) - km,ctran_Cost of a combined monthly ticket (all modes of public transport) for 5-10 km in the central zone - EUR,ctran_Cost of a taxi ride of 5 km to the centre at day time - EUR
0,Amsterdam (greater city),NaN,NaN,NaN,NaN,2.50,0.0,3.5,1917.0,22.4,...,NaN,303.16,325509.0,0.16,16.0,262103.00,98218.00,1154.4,NaN,NaN
1,Antwerpen (greater city),5.0,17.6,4.2,759.8,NaN,0.0,19.0,NaN,28.4,...,NaN,401.43,219900.0,0.16,9.0,NaN,NaN,575.8,49.00,15.0
2,Barcelona (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,278.97,741737.0,0.16,42.0,NaN,NaN,NaN,NaN,NaN
3,Basel (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.85,387.23,136770.0,0.20,7.0,48180.45,23183.99,NaN,90.00,28.0
4,Berlin,5.4,18.6,-0.5,568.1,8.33,0.0,13.5,3356.0,23.0,...,12.60,282.69,1061565.0,0.15,55.0,321219.00,185723.00,1073473.0,63.42,17.3

In [6]:
# wir erstellen eine Filterliste. Erstes Objekt: die Städtenamen. Zweites: Einwohnerzahl. 
lst = ['cities', 'cpop1_Population on the 1st of January, total']

for col in df_full.columns:
    # filtern nach ctran und zur liste hinzufügen
    if 'ctran' in col:
        lst.append(col)

In [7]:
#Spalten anhand der Filterliste anzeigen. in neuem df abspeichern
df = df_full[lst]
df

,cities,"cpop1_Population on the 1st of January, total",ctran_Share of journeys to work by car -%,ctran_Share of journeys to work by motorcycle -%,ctran_Share of journeys to work by bicycle -%,ctran_Share of journeys to work by foot -%,"ctran_Share of journeys to work by public transport (rail, metro, bus, tram) -%",ctran_Share of journeys to work by car or motorcycle -%,ctran_Average time of journey to work - minutes,ctran_Average length of journey to work by private car - km,ctran_Number of registered cars per 1000 population,ctran_Number of private cars registered,ctran_People killed in road accidents per 10000 pop.,ctran_Number of deaths in road accidents,ctran_People commuting into the city,ctran_People commuting out of the city,ctran_Length of bicycle network (dedicated cycle paths and lanes) - km,ctran_Cost of a combined monthly ticket (all modes of public transport) for 5-10 km in the central zone - EUR,ctran_Cost of a taxi ride of 5 km to the centre at day time - EUR
0,Amsterdam (greater city),1073736.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,303.16,325509.0,0.16,16.0,262103.00,98218.00,1154.40,NaN,NaN
1,Antwerpen (greater city),547794.0,NaN,NaN,NaN,NaN,20.70,55.89,NaN,NaN,401.43,219900.0,0.16,9.0,NaN,NaN,575.80,49.00,15.00
2,Barcelona (greater city),2658830.0,37.03,4.28,1.72,14.16,24.29,41.30,27.18,NaN,278.97,741737.0,0.16,42.0,NaN,NaN,NaN,NaN,NaN
3,Basel (greater city),355946.0,26.37,1.77,19.34,7.52,45.00,28.14,33.14,11.85,387.23,136770.0,0.20,7.0,48180.45,23183.99,NaN,90.00,28.00
4,Berlin,3685265.0,37.70,1.40,12.80,5.80,42.40,39.00,32.50,12.60,282.69,1061565.0,0.15,55.0,321219.00,185723.00,1073473.00,63.42,17.30
5,Birmingham,1139249.0,63.80,0.50,1.60,10.40,23.00,64.30,NaN,NaN,330.57,376607.0,0.12,14.0,NaN,NaN,233.00,102.67,NaN
6,Bratislava (greater city),475577.0,NaN,NaN,NaN,NaN,NaN,NaN,23.50,NaN,400.28,190336.0,0.16,7.0,141694.00,12931.00,122.06,26.90,4.59
7,Brno,379466.0,NaN,NaN,NaN,NaN,NaN,NaN,36.00,NaN,424.73,160959.0,0.21,8.0,55778.00,11467.00,39.00,21.87,7.16
8,Bruxelles/Brussel (greater city),1264371.0,48.50,1.20,1.90,4.10,40.30,49.70,NaN,NaN,394.55,498855.0,0.09,11.0,NaN,NaN,513.00,60.00,15.00
9,Budapest (greater city),1686222.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,428.99,723372.0,0.23,38.0,NaN,NaN,213.00,22.65,7.59
10,Cork (greater city),118713.0,59.90,0.70,2.90,23.30,9.20,60.50,20.40,11.10,NaN,58357.0,NaN,3.0,39006.00,10419.00,14.60,NaN,10.00
11,Debrecen,201704.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,404.21,81531.0,0.40,8.0,NaN,NaN,123.00,21.13,6.71
12,Dublin (greater city),1325700.0,55.60,1.00,5.30,13.50,21.00,56.50,28.80,10.30,NaN,411836.0,NaN,11.0,276434.00,194385.00,517.00,NaN,12.00
13,Geneva (greater city),437406.0,20.86,6.00,11.71,11.62,49.82,26.86,36.08,11.20,380.55,164293.0,0.21,9.0,47647.22,15544.68,NaN,73.00,23.00
14,Gent,270133.0,NaN,NaN,NaN,NaN,14.27,64.56,NaN,NaN,400.40,108162.0,0.56,15.0,NaN,NaN,496.30,49.00,16.00
15,Glasgow,623715.0,52.98,0.18,1.82,13.40,30.87,53.16,NaN,NaN,291.15,181596.0,0.13,8.0,NaN,NaN,NaN,NaN,NaN
16,Graz,269997.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.33,9.0,NaN,NaN,NaN,NaN,NaN
17,Hamburg,1862565.0,41.10,0.90,11.60,6.00,40.40,41.90,30.10,11.90,341.23,645645.0,0.21,39.0,354483.00,129424.00,652197.00,89.50,15.90
18,Košice (greater city),227458.0,NaN,NaN,NaN,NaN,NaN,NaN,19.20,NaN,317.52,72724.0,0.13,3.0,53553.00,9956.00,180.70,25.00,4.65
19,Kraków,806201.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,722.86,582769.0,0.12,10.0,NaN,NaN,318.80,22.06,3.71
20,Limerick (greater city),56980.0,65.00,0.30,2.80,22.40,5.30,65.30,19.70,12.50,NaN,21369.0,NaN,1.0,15213.00,6182.00,15.70,NaN,10.00
21,Linz (greater city),193814.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.41,8.0,NaN,NaN,NaN,NaN,NaN
22,Lisboa (greater city),1965363.0,55.28,0.97,0.18,8.58,33.76,56.26,33.24,NaN,NaN,NaN,0.18,34.0,637113.00,435522.00,NaN,49.30,NaN
23,Ljubljana,297575.0,75.00,NaN,NaN,NaN,9.60,75.60,30.36,26.49,546.43,162605.0,0.07,2.0,NaN,NaN,362.00,37.00,6.20
24,London,8866541.0,31.90,1.20,4.30,9.30,52.60,33.10,NaN,NaN,282.79,2507333.0,0.13,112.0,NaN,NaN,NaN,NaN,NaN
25,Luxembourg (greater city),115227.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Lyon (greater city),1296104.0,49.00,1.50,6.70,10.10,32.70,50.50,29.00,14.00,431.68,559497.0,0.15,19.0,212389.00,84197.00,NaN,NaN,12.80
27,Madrid (greater city),4501429.0,NaN,NaN,NaN,NaN,NaN,40.60,31.21,NaN,396.65,1785501.0,0.15,66.0,NaN,NaN,284.00,51.30,NaN
28,Maribor,113747.0,82.60,NaN,NaN,NaN,NaN,82.60,22.38,19.39,521.72,59344.0,0.18,2.0,NaN,NaN,146.00,36.00,7.23
29,Marseille (greater city),976483.0,57.60,5.30,2.00,9.30,25.70,63.00,35.00,19.00,427.17,417126.0,0.34,33.0,84252.00,48594.00,NaN,NaN,13.25
30,Milano (greater city),3565055.0,59.07,4.77,4.75,8.26,23.13,63.84,34.80,NaN,585.18,2086015.0,0.29,102.0,1031817.00,742995.00,312.00,NaN,NaN
31,München,1505005.0,35.40,1.40,12.80,6.40,44.00,36.80,26.90,11.30,345.61,522736.0,0.11,16.0,393827.00,186104.00,525439.00,62.50,17.00
32,Napoli (greater city),2977204.0,59.31,5.88,0.99,17.28,16.51,65.20,28.11,NaN,644.58,1922891.0,0.34,100.0,470183.00,457396.00,19.20,NaN,NaN
33,Ostrava,279791.0,NaN,NaN,NaN,NaN,NaN,NaN,36.00,NaN,378.48,113400.0,0.31,9.0,35663.00,8339.00,79.00,18.01,6.16
34,Paris (greater city),10353710.0,35.70,3.30,3.40,7.80,49.90,39.00,44.00,27.00,356.17,3687726.0,0.17,175.0,722207.00,223247.00,NaN,NaN,9.10
35,Porto (greater city),1017569.0,63.70,0.96,0.29,11.05,22.16,64.66,25.21,NaN,NaN,NaN,0.22,22.0,254262.00,213077.00,NaN,36.00,NaN
36,Praha,1275406.0,NaN,NaN,NaN,NaN,NaN,NaN,38.00,NaN,540.67,671335.0,0.13,17.0,142617.00,24291.00,224.00,21.87,6.96
37,Prešov,83897.0,NaN,NaN,NaN,NaN,NaN,NaN,19.20,NaN,292.63,24822.0,0.11,1.0,30709.00,9707.00,15.40,16.60,5.11
38,Rijeka,102415.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,495.76,50773.0,0.29,3.0,NaN,NaN,0.00,48.00,9.00
39,Roma,2747290.0,54.63,10.07,0.50,6.97,27.81,64.70,44.74,NaN,675.65,1859222.0,0.49,134.0,238494.00,48727.00,320.00,NaN,7.40
40,Rotterdam (greater city),1274944.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,413.86,527642.0,0.19,24.0,204196.00,87752.00,1646.50,NaN,NaN
41,Split (greater city),180568.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,435.32,78605.0,0.11,2.0,NaN,NaN,17.00,60.00,9.00
42,Szeged,157930.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,385.24,60841.0,0.44,7.0,NaN,NaN,61.00,24.29,6.58
43,Valencia (greater city),1474632.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,390.50,575845.0,0.14,21.0,NaN,NaN,NaN,NaN,NaN
44,Warszawa,1861599.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,845.97,1574854.0,0.16,29.0,NaN,NaN,773.40,24.40,4.47
45,Wien (greater city),1766746.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.12,21.0,NaN,NaN,NaN,NaN,NaN
46,Zagreb,760020.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,390.42,296727.0,0.36,27.0,NaN,NaN,427.00,53.00,8.00
47,Zurich (greater city),725893.0,26.83,1.05,6.77,4.94,60.41,27.88,39.90,16.28,407.99,294192.0,0.26,19.0,238202.43,62484.90,NaN,91.00,35.00
48,Łódź,652015.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,681.02,444038.0,0.29,19.0,NaN,NaN,245.30,21.12,3.47

In [ ]:
df.columns

### Quizz

    1. Balkenchart - Autostadt
        a) sortiere den df nach den meisten einwohner  & zeige die ersten 10 an
        b) speichere das Ergebnis in einem df ```df_autofrei```
        c) erstelle einen Balkenchart mit der anzahl Autos pro 1000 Einwohner auf der x achse und den Städten auf der y-Achse
        d) passe die Properies an so dass man etwas sieht
        e) sortiere die Balken aufsteigend (grösste zuoberst)
        f) setze einen aussagekräftigen Titel
        g) setze ein Tootip

In [8]:
df_autofrei = df.sort_values('cpop1_Population on the 1st of January, total', ascending=False).head(10)

In [ ]:
alt.Chart(df_autofrei).mark_bar().encode(
    x = 'ctran_Number of registered cars per 1000 population', 
    y = alt.Y('cities', sort='-x'), 
    tooltip=['cities', 'ctran_Number of registered cars per 1000 population']
).properties(
    width = 800, 
    height = 500, 
    title = "Anzahl Autos pro 1000 Einwohner in den 10 grössten Städten im Datensatz"
)

2. Scatterplot - Unfälle

        a) erstelle einen Scatterplot mit Anzahl Autos pro 1000 Einwohner vs nutzung des öffentlichen Verkehrs in Prozent
        b) wie oben, passe die Grösse, Titel und Tooltip an
        c) mache die Punkte grösser z.B [```mark_circle(size=300)```]
        d) ändere die Farbe der Punkte nach nutzung des öffentlichen Verkehrs und setze die Farbskala "greenblue"

In [ ]:
alt.Chart(df).mark_circle(size=300, 
                        ).encode(
    x = 'ctran_Number of registered cars per 1000 population', 
    y = 'ctran_Share of journeys to work by public transport (rail, metro, bus, tram) -%', 
    tooltip=['cities', 'ctran_Number of registered cars per 1000 population','ctran_Share of journeys to work by public transport (rail, metro, bus, tram) -%' ], 
    color = alt.Color('ctran_Share of journeys to work by public transport (rail, metro, bus, tram) -%:Q').scale(scheme ='greenblue')
).properties(
    width = 500, 
    height = 500, 
    title = "Anzahl Autos pro 1000 Einwohner vs Nutzung Öffentlicher Verkehr"
)
#