# 02 Formatting

* Sortierung von Achsen
* Datatypes für Altair
* Farben
* Formatierung

In [1]:
#import libraries
import altair as alt
import pandas as pd

In [27]:
df = pd.read_csv('data/pokemon/pokemon_gen1.csv')

### Order
Mit `alt.Y('col', sort='-x' )` können wir Achsen sortieren.

In [28]:
df_top_height = df.sort_values('height_m', ascending = False).head(10)
df_top_height.head(2)

,name,type1,type2,classfication,height_m,weight_kg,year,is_legendary,attack,speed,hp,base_happiness,capture_rate
94,Onix,rock,ground,Rock Snake Pokémon,8.8,210.0,1996,0,45,70,35,70,45
129,Gyarados,water,flying,Atrocious Pokémon,6.5,235.0,1996,0,155,81,95,70,45

In [29]:
# Order
alt.Chart(df_top_height).mark_bar().encode(
    x = 'height_m',
    y = alt.Y('name', sort='-x'), 
)

alt.Chart(...)


### Datatypes
Wir können Altair mitgeben, als was für einen Datentypen er eine Spalte behandeln soll.

* `Q`: quantitative data - numeric values
* `O`: ordinal data - ordered categories (e.g. Generation 1,2,3)
* `N`: nominal data - categories with no order (e.g. type1 seed, rock, water...)
* `T`: temporal data

In [30]:
# Bar chart: wir fügen Farbe hinzu
alt.Chart(df_top_height).mark_bar().encode(
    x = 'height_m',
    y = alt.Y('name', sort='-x' ), 
    color='height_m:Q'
)

alt.Chart(...)

## Farben

`alt.Color('col').scale(scheme='your_scheme')` können wir Farbschemas festlegen. 

Eine Auswahl
* viridis
* magma
* plasma
* turbo
* yelloworangebrown
* purplered
* purplebluegreen
* blueorange

[Mehr Farbschemas](https://vega.github.io/vega/docs/schemes/)

In [31]:
alt.Chart(df_top_height).mark_bar().encode(
    x = 'height_m',
    y = alt.Y('name', sort='-x' ), 
    color=alt.Color('height_m:Q').scale(scheme='purplered')
)

alt.Chart(...)

### Eigene Farbskalen

Wir können je eine Liste für die Werte die eingefärtbt werden (domain) und eine mit den Farben erstellen (range). Und Altair macht uns daraus eine eigene Farbskala. 

Wichtig: beide Listen müssen gleich lang sein.

In [32]:
df.head(1)

,name,type1,type2,classfication,height_m,weight_kg,year,is_legendary,attack,speed,hp,base_happiness,capture_rate
0,Bulbasaur,grass,poison,Seed Pokémon,0.7,6.9,1996,0,49,45,45,70,45

In [33]:
df['speed'].min()

15

In [34]:
domain = [15, 150]
range = ['blue', 'orange']

alt.Chart(df).mark_point().encode(
    x = 'speed', 
    y = 'height_m', 
    color = alt.Color('speed').scale(domain=domain, range=range)
)

alt.Chart(...)

#### Mit Farben Werte gruppieren
Wir können unter color eine zusätzliche Spalte angeben, nach Welcher die Werte eingefärbt werden.

In [35]:
alt.Chart(df).mark_bar().encode(
    x = 'height_m',
    y = alt.Y('type1', sort='-x' ), 
    color='is_legendary:N'
)

alt.Chart(...)

### Mehrere Generationen Pokemons

`df_generation_type` unten zeigt für jede Generation von Pokemons an, wie viele Wasser, Normale, Gift-Pokemon es gab.

In [ ]:
df_raw = pd.read_csv("data/pokemon/pokemon.csv")
df_generation_type = df_raw.groupby('generation')['type1'].value_counts().reset_index()
df_generation_type

### Quizz


1. Mache einen Barchart mit Generation 1 - 7 auf der Y Achse und Anzahl Pokemon insgesamt auf der X Achse. (Tip: Datentypen)
2. Füge Farbe nach type1 hinzu. Experimentiere mit Datentypen bei der Farbe
3. Ändere das Farbschema.

In [41]:
alt.Chart(df_generation_type).mark_bar().encode(
    x = 'count', 
    y = 'generation:N',
    color = alt.Color('type1:N').scale(scheme = 'blueorange')
)

alt.Chart(...)

4. Kehre den Plot um und plotte 
* X-Achse: count, 
* Y-Achse: type1
* Farbe: generation

5. Sortiere die Y-Achse absteigend nach den Werten der X-Achse

In [42]:
alt.Chart(df_generation_type).mark_bar().encode(
    x = 'count', 
    y = alt.Y('type1', sort='-x'),
    color = alt.Color('generation').scale(scheme = 'blueorange')
)

alt.Chart(...)

6. Erstelle deine eigene Farbskala für den plot und färbe damit Generation 1-7 ein. <br>
... Teste auch hier verschiedene Datentypen für die Farbe.

In [43]:
domain = [1, 3.5, 7]
range = ['lightgreen', 'orange', 'purple']

In [44]:
alt.Chart(df_generation_type).mark_bar().encode(
    x = 'count', 
    y = alt.Y('type1', sort='-x'),
    color = alt.Color('generation:Q').scale(domain=domain, range = range)
)

alt.Chart(...)

## Eigenschaften anpassen

In [45]:
alt.Chart(df_generation_type).mark_bar().encode(
    x = 'count', 
    y = alt.Y('type1', sort='-x'),
    color = alt.Color('generation').scale(domain=domain, range = range)
).properties(
    width = 600, 
    height = 350, 
    title = "Pokemon nach Typ und Generation" 
    
)

alt.Chart(...)

#### Mehr Formatierung

Hier gibt es eine [Dokumentation für mehr Formatierung](https://altair-viz.github.io/user_guide/customization.html#adjusting-the-title)

Achsen
* `.scale(zero=False)`: schneidet Achse auf effektive Werte zu (statt bei 0 anzufangen)
* `.title('<Achsenname>')`: lässt uns Achsen neu bennenen
Titel
* `alt.Title()`: Damit können wir Subtitel einfügen und die Platzierung des Titels bestimmen
Legende
* `legend(orient="left")`: Orientierung der Legende
* `.title('<name>')`: Name der Legende, `None` für keinen Titel

In [46]:
# Mehr Formatierung 
alt.Chart(df_generation_type).mark_bar().encode(
    x = alt.X('count').title('Anzahl'), 
    y = alt.Y('type1', sort='-x').title('Pokemontyp'),
    color = alt.Color('generation').scale(domain=domain, range = range).legend(orient="left").title(None),
    tooltip=['type1', 'count']
).properties(
    width = 600, 
    height = 350, 
    title = alt.Title("Pokemon nach Typ und Generation",
       subtitle="Inklusive Subtitel",
       anchor='start', # <- rechts- oder links-bündig
       orient='top', # <- oben/ unten
       offset=20 # <- Abstand zum Chart
       )
)

alt.Chart(...)

## Export

In [47]:
# Wir können die ganze Grafik in einer Variablen speichern. 

my_chart = alt.Chart(df_generation_type).mark_bar().encode(
    x = alt.X('count').title('Anzahl'), 
    y = alt.Y('type1', sort='-x').title('Pokemontyp'),
    color = alt.Color('generation').scale(domain=domain, range = range).legend(orient="left").title(None),
    tooltip=['type1', 'count']
).properties(
    width = 600, 
    height = 350, 
    title = alt.Title("Pokemon nach Typ und Generation",
       subtitle="Inklusive Subtitel",
       anchor='start', # <- rechts- oder links-bündig
       orient='top', # <- oben/ unten
       offset=20 # <- Abstand zum Chart
       )
)

In [22]:
my_chart

alt.Chart(...)

In [23]:
# Abspeichern als html
my_chart.save('charts/pokemon_type_generation.html', inline=True)

In [24]:
# als png speichern
my_chart.save('charts/pokemon_type_generation.png')

In [25]:
# als svg speichern
my_chart.save('charts/pokemon_type_generation.svg')

In [26]:
# als pdf speichern
my_chart.save('charts/pokemon_type_generation.pdf')